### ISSUE TITLE
Lunch and Coffee Breaks

### ISSUE THREAD

**Issue by pautasso** [apiacademy/WSREST2016#2]
Hi Erik,

just to let you know that we would like all workshops to synchronize their schedule concerning lunch and coffee breaks.

The schedule thus is the one like in previous days of the conference.

9:00 start
10:30-11:00 coffee break (this one you got right)
13:00-14:00 lunch (half hour later than what you have in the agenda)
15:30-16:00 coffee break (half hour later than what you have in the agenda)
17:30 close (which is fine)

For some reason, I could not edit the agenda wiki page, but I hope you can.

Thanks
Cesare

**Comment by mamund** [comment]
Cesare:

thanks for the assist on the sked. I've updated our agenda and we'll be sure to align our breaks.

hope to see you at WS-REST this year!
